version: '3.9'

services:
  postgres:
    image: postgres:16.1-bullseye
    container_name: postgres-16
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: no


